name: CI

on:
  push:
    branches:
      - main
      - master
      - 'v*'
    # always run CI for tags
    tags:
      - '*'
  pull_request: {}

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: "Tests - ${{ matrix.os }} - Node ${{ matrix.node-version }}"
    runs-on: "${{ matrix.os }}-latest"

    strategy:
      matrix:
        os: [ubuntu]
        node-version: ['10.x', '12.x']

    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v3.0.0-beta.1
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn install --frozen-lockfile --non-interactive
      - run: yarn test

  floating-dependencies:
    name: "Floating Deps"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v3.0.0-beta.1

      - run: yarn install --no-lockfile
      - run: yarn test
